### ISSUE TITLE
Blood fountains don't follow BLUDTYPE

### ISSUE THREAD

**Issue by PopeRigby** [nashmuhandes/nashgore#16]

**Comment by nashmuhandes** [comment]
@PopeRigby can you please elaborate on what you mean by this? BLUDTYPE's only purpose is to help re-map non-standard blood actors that gets spawned when something gets shot at. I'm not sure what you mean by "blood fountain".

**Comment by PopeRigby** [comment]
Yeah, I don't know what I was talking about now.
